useDotenv: true
service: sasta-drive-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  httpApi:
    name: sastaDriveApi-${sls:stage}
  environment:
    DB_URL: ${env:DB_URL}
    REDIS_URL: ${env:REDIS_URL}
    BLACK_BLAZE_ENDPOINT: ${env:BLACK_BLAZE_ENDPOINT}
    BLACK_BLAZE_REGION: ${env:BLACK_BLAZE_REGION}
    BLACK_BLAZE_ACCESS_KEY_ID: ${env:BLACK_BLAZE_ACCESS_KEY_ID}
    BLACK_BLAZE_SECRET: ${env:BLACK_BLAZE_SECRET}
    BUCKET_NAME: ${env:BUCKET_NAME}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    SESSION_SECRET: ${env:SESSION_SECRET}
    CLIENT_URL_1: ${env:CLIENT_URL_1}
    CLIENT_URL_2: ${env:CLIENT_URL_2}
    RESEND_KEY: ${env:RESEND_KEY}
    RAZORPAY_WEBHOOK_SECRET: ${env:RAZORPAY_WEBHOOK_SECRET}
    RAZORPAY_ID: ${env:RAZORPAY_ID}
    RAZORPAY_SECRET: ${env:RAZORPAY_SECRET}
    S3_THUMBNAIL_BUCKET: ${env:S3_THUMBNAIL_BUCKET}
    S3_THUMBNAIL_REGION: ${env:S3_THUMBNAIL_REGION}
    S3_THUMBNAIL_ACCESS_KEY_ID: ${env:S3_THUMBNAIL_ACCESS_KEY_ID}
    S3_THUMBNAIL_SECRET: ${env:S3_THUMBNAIL_SECRET}

package:
  individually: true

functions:
  backend:
    memorySize: 512
    timeout: 10
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{proxy+}
    name: sastaDriveBackend-${sls:stage}
    handler: lambda.handler
    package:
      patterns:
        - "!.git/**"
        - "!.env"
        - "!.env.*"
        - "!*.log"
        - "!serverless.yml"
        - "!lambda/**"
        - "!server.js"
        - "!worker/**"
        - "!.github/**"

  fileCleaner:
    memorySize: 1024
    timeout: 600
    name: sastaDriveFileCleaner-${sls:stage}
    handler: lambda/fileDeletionFunction/handler.handler
    events:
    - schedule:
        rate: cron(0 0 * * ? *)
    package:
      patterns:
        - "!**"
        - "lambda/fileDeletionFunction/**"
        - "lambda/db.js"
        - "lambda/models/**"
        - "lambda/s3Client.js"
        - "lambda/package.json"
        - "lambda/package-lock.json"
        - "lambda/node_modules/**"
        - "lambda/thumbnailClient.js"
    
  trashCleaner:
    memorySize: 1024
    timeout: 600
    name: sastaDriveTrashCleaner-${sls:stage}
    handler: lambda/trashCleanupFunction/handler.handler
    events:
    - schedule:
        rate: cron(0 0 * * ? *)
    package:
      patterns:
        - "!**"
        - "lambda/trashCleanupFunction/**"
        - "lambda/db.js"
        - "lambda/models/**"
        - "lambda/s3Client.js"
        - "lambda/package.json"
        - "lambda/package-lock.json"
        - "lambda/node_modules/**"
        - "lambda/thumbnailClient.js"

  warningFunction:
    memorySize: 400
    timeout: 180
    name: sastaDriveWarning-${sls:stage}
    handler: lambda/warningFunction/handler.handler
    events:
    - schedule:
        rate: cron(0 0 * * ? *)
    package:
      patterns:
        - "!**"
        - "lambda/warningFunction/**"
        - "lambda/db.js"
        - "lambda/models/**"
        - "lambda/s3Client.js"
        - "lambda/package.json"
        - "lambda/package-lock.json"
        - "lambda/node_modules/**"
