export const NOTIFICATION_TYPES = {
  // FILE
  FILE_UPLOAD_SUCCESS: "FILE_UPLOAD_SUCCESS",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_DELETED: "FILE_DELETED",
  FILE_PERMANENTLY_DELETED: "FILE_PERMANENTLY_DELETED",
  FILE_MOVED: "FILE_MOVED",

  // ACCOUNT & SECURITY
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  EMAIL_CHANGED: "EMAIL_CHANGED",

  // STORAGE
  STORAGE_80_PERCENT: "STORAGE_80_PERCENT",
  STORAGE_90_PERCENT: "STORAGE_90_PERCENT",
  STORAGE_FULL: "STORAGE_FULL",

  // SYSTEM
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  FEATURE_ANNOUNCEMENT: "FEATURE_ANNOUNCEMENT",

  // BILLING (future)
  PLAN_UPGRADED: "PLAN_UPGRADED",
  PLAN_DOWNGRADED: "PLAN_DOWNGRADED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
};
